version: "3.9"

services:
  backend:
    build:
      context: ./newBackend
      dockerfile: Dockerfile
    container_name: kavach-backend
    ports:
      - "5000:5000"
    volumes:
      - ./newBackend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: kavach-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo:6
    container_name: kavach-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
